In [13]:
import pandas as pd
df=pd.read_csv("C:/Users/HYDERA/Desktop/HYPERTENSION/india/ctg-studies.csv")
df.head()

,NCT Number,Study Title,Study URL,Acronym,Study Status,Brief Summary,Study Results,Conditions,Interventions,Primary Outcome Measures,...,Study Design,Other IDs,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents
0,NCT03555344,Effect of Mantra on Hypertensive Patients,https://clinicaltrials.gov/study/NCT03555344,NaN,COMPLETED,Mantras are specialized energized sound or wor...,NO,High Blood Pressure,OTHER: Mantra Chikitsa,"Systolic Blood Pressure, Change from baseline ...",...,Allocation: RANDOMIZED | Intervention Model: P...,NMP/10164,2017-10-28,2018-05-15,2018-05-30,2018-06-13,NaN,2018-07-17,"NMP Medical Research Institute, Jaipur, Rajast...",NaN
1,NCT01112306,ACT-293987 in Pulmonary Arterial Hypertension,https://clinicaltrials.gov/study/NCT01112306,NaN,COMPLETED,"Long-term, single-arm, multicenter, open-label...",YES,Pulmonary Arterial Hypertension,DRUG: ACT-293987,Number of Participants With Treatment-emergent...,...,Allocation: NA | Intervention Model: SINGLE_GR...,AC-065A303|2009-014992-31,2010-07-07,2021-08-26,2021-08-26,2010-04-28,2022-09-19,2025-03-30,"Mobile, Alabama, United States|Phoenix, Arizon...","Study Protocol, https://cdn.clinicaltrials.gov..."
2,NCT01106014,Selexipag (ACT-293987) in Pulmonary Arterial H...,https://clinicaltrials.gov/study/NCT01106014,GRIPHON,COMPLETED,The AC-065A302 (GRIPHON) study is an event-dri...,YES,Pulmonary Arterial Hypertension,DRUG: Selexipag|DRUG: Placebo,Time From Randomization to the First Morbidity...,...,Allocation: RANDOMIZED | Intervention Model: P...,AC-065A302,2009-12-01,2014-04-01,2014-10-01,2010-04-19,2016-03-01,2025-10-27,"University of South Alabama, Mobile, Alabama, ...",NaN
3,NCT00660179,Study of Macitentan (ACT-064992) on Morbidity ...,https://clinicaltrials.gov/study/NCT00660179,SERAPHIN,COMPLETED,The AC-055-302/SERAPHIN study will be an event...,YES,Pulmonary Arterial Hypertension,DRUG: macitentan (ACT-064992)|DRUG: macitentan...,Time to First Confirmed Morbidity or Mortality...,...,Allocation: RANDOMIZED | Intervention Model: P...,AC-055-302,2008-05,2012-03,2012-04,2008-04-17,2014-05-05,2015-09-28,"University of Alabama at Birmingham, Birmingha...",NaN
4,NCT00494533,Study of Intravenous Remodulin in Patients in ...,https://clinicaltrials.gov/study/NCT00494533,TRUST-1,TERMINATED,"Multi-center, double-blind, placebo-controlled...",NO,Pulmonary Arterial Hypertension,DRUG: Remodulin (treprostinil sodium),"Six-minute walk distance, Placebo-corrected ch...",...,Allocation: RANDOMIZED | Intervention Model: P...,RIV-PH-402,2005-03,2005-10,2005-10,2007-06-29,NaN,2014-01-29,"SAL Hospital & Medical Institute, Ahmedabad, I...",NaN

In [14]:
df.shape

(172, 30)

In [15]:
df.info

<bound method DataFrame.info of       NCT Number                                        Study Title  \
0    NCT03555344          Effect of Mantra on Hypertensive Patients
1    NCT01112306      ACT-293987 in Pulmonary Arterial Hypertension
2    NCT01106014  Selexipag (ACT-293987) in Pulmonary Arterial H...
3    NCT00660179  Study of Macitentan (ACT-064992) on Morbidity ...
4    NCT00494533  Study of Intravenous Remodulin in Patients in ...
..           ...                                                ...
167  NCT01138865  Effect of CPAP on Biomarkers in Patients With OSA
168  NCT01480544  Improving Maternal and Child Health in India: ...
169  NCT00694616  Prevalence of Metabolic Syndrome in Obstructiv...
170  NCT07337850  Prospective Evaluation of 68Ga-FAPI PET in Bil...
171  NCT06041906  International Registry of Congenital Portosyst...

                                        Study URL    Acronym  \
0    https://clinicaltrials.gov/study/NCT03555344        NaN
1    https://clinicaltrials.gov/study/NCT01112306        NaN
2    https://clinicaltrials.gov/study/NCT01106014    GRIPHON
3    https://clinicaltrials.gov/study/NCT00660179   SERAPHIN
4    https://clinicaltrials.gov/study/NCT00494533    TRUST-1
..                                            ...        ...
167  https://clinicaltrials.gov/study/NCT01138865       CPAP
168  https://clinicaltrials.gov/study/NCT01480544  IMATCHINE
169  https://clinicaltrials.gov/study/NCT00694616        NaN
170  https://clinicaltrials.gov/study/NCT07337850     FAPi-2
171  https://clinicaltrials.gov/study/NCT06041906     IRCPSS

                Study Status  \
0                  COMPLETED
1                  COMPLETED
2                  COMPLETED
3                  COMPLETED
4                 TERMINATED
..                       ...
167                  UNKNOWN
168                COMPLETED
169                COMPLETED
170               RECRUITING
171  ENROLLING_BY_INVITATION

                                         Brief Summary Study Results  \
0    Mantras are specialized energized sound or wor...            NO
1    Long-term, single-arm, multicenter, open-label...           YES
2    The AC-065A302 (GRIPHON) study is an event-dri...           YES
3    The AC-055-302/SERAPHIN study will be an event...           YES
4    Multi-center, double-blind, placebo-controlled...            NO
..                                                 ...           ...
167  CPAP, the standard treatment for Obstructive s...            NO
168  The study evaluates the impact of a new condit...            NO
169  Metabolic syndrome is a constellation of risk ...            NO
170  The goal of this prospective observational stu...            NO
171  Congenital Portosystemic Shunt (CPSS) is a rar...            NO

                                            Conditions  \
0                                  High Blood Pressure
1                      Pulmonary Arterial Hypertension
2                      Pulmonary Arterial Hypertension
3                      Pulmonary Arterial Hypertension
4                      Pulmonary Arterial Hypertension
..                                                 ...
167                            Obstructive Sleep Apnea
168  Obstetric Labor Complications|Post-partum Hemo...
169         Obstructive Sleep Apnea|Metabolic Syndrome
170  Gall Bladder Cancer|Intrahepatic Cholangiocarc...
171  Congenital Portosystemic Shunt|CPSS (Congenita...

                                         Interventions  \
0                               OTHER: Mantra Chikitsa
1                                     DRUG: ACT-293987
2                        DRUG: Selexipag|DRUG: Placebo
3    DRUG: macitentan (ACT-064992)|DRUG: macitentan...
4                DRUG: Remodulin (treprostinil sodium)
..                                                 ...
167  DEVICE: AutoSet Spirit--Wash--Modified-AutoSet...
168  OTHER: Experimental: Treatment 1|OTHER: Experi...
169  DEVICE: AutoSet Spirit|DEVICE: Modified-AutoSe...
170  DIAGNOSTIC_TEST: gallium-68-Fibroblast Activat...
171                           PROCEDURE: Shunt Closure

                              Primary Outcome Measures  ...  \
0    Systolic Blood Pressure, Change from baseline ...  ...
1    Number of Participants With Treatment-emergent...  ...
2    Time From Randomization to the First Morbidity...  ...
3    Time to First Confirmed Morbidity or Mortality...  ...
4    Six-minute walk distance, Placebo-corrected ch...  ...
..                                                 ...  ...
167  Effect of CPAP therapy on blood pressure, 7 mo...  ...
168  Increase institutional deliveries and improve ...  ...
169  Proportion of subjects satisfying the National...  ...
170  Diagnostic accuracy of Ga-68 FAPI PET/CT for d...  ...
171  Numbers of patients with spontaneous shunt clo...  ...

                                          Study Design  \
0    Allocation: RANDOMIZED | Intervention Model: P...
1    Allocation: NA | Intervention Model: SINGLE_GR...
2    Allocation: RANDOMIZED | Intervention Model: P...
3    Allocation: RANDOMIZED | Intervention Model: P...
4    Allocation: RANDOMIZED | Intervention Model: P...
..                                                 ...
167  Allocation: RANDOMIZED | Intervention Model: C...
168  Allocation: RANDOMIZED | Intervention Model: P...
169  Allocation: RANDOMIZED | Intervention Model: C...
170  Observational Model: OTHER | Time Perspective:...
171  Observational Model: COHORT | Time Perspective...

                     Other IDs  Start Date Primary Completion Date  \
0                    NMP/10164  2017-10-28              2018-05-15
1    AC-065A303|2009-014992-31  2010-07-07              2021-08-26
2                   AC-065A302  2009-12-01              2014-04-01
3                   AC-055-302     2008-05                 2012-03
4                   RIV-PH-402     2005-03                 2005-10
..                         ...         ...                     ...
167         SKS/CPAP-OSAS/2009     2012-03                 2014-09
168                Pro00031046     2012-08                 2014-12
169          SKS/OSA/CPAP/2008     2008-07                 2010-05
170       Study no:- 4455|6429  2024-09-25                 2026-03
171                 2018-00413  2018-04-26              2026-10-26

    Completion Date First Posted Results First Posted  Last Update Posted  \
0        2018-05-30   2018-06-13                  NaN          2018-07-17
1        2021-08-26   2010-04-28           2022-09-19          2025-03-30
2        2014-10-01   2010-04-19           2016-03-01          2025-10-27
3           2012-04   2008-04-17           2014-05-05          2015-09-28
4           2005-10   2007-06-29                  NaN          2014-01-29
..              ...          ...                  ...                 ...
167         2015-03   2010-06-08                  NaN          2013-06-24
168         2015-11   2011-11-29                  NaN          2015-12-16
169         2010-12   2008-06-10                  NaN          2013-06-25
170         2026-03   2026-01-13                  NaN          2026-01-13
171      2028-12-31   2023-09-18                  NaN          2025-06-18

                                             Locations  \
0    NMP Medical Research Institute, Jaipur, Rajast...
1    Mobile, Alabama, United States|Phoenix, Arizon...
2    University of South Alabama, Mobile, Alabama, ...
3    University of Alabama at Birmingham, Birmingha...
4    SAL Hospital & Medical Institute, Ahmedabad, I...
..                                                 ...
167  All India Institute of Medical Sciences, New D...
168             Imatchine, Bangalore, Karnataka, India
169  All India Institute of Medical Sciences, New D...
170  Dr.Shraddha Patkar, Mumbai, Maharashtra, 40001...
171  Yale University School of Medicine, New Haven,...

                                       Study Documents
0                                                  NaN
1    Study Protocol, https://cdn.clinicaltrials.gov...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
167                                                NaN
168                                                NaN
169                                                NaN
170                                                NaN
171                                                NaN

[172 rows x 30 columns]>

In [16]:
df.isnull().sum()

NCT Number                      0
Study Title                     0
Study URL                       0
Acronym                       106
Study Status                    0
Brief Summary                   0
Study Results                   0
Conditions                      0
Interventions                  14
Primary Outcome Measures        2
Secondary Outcome Measures     33
Other Outcome Measures        155
Sponsor                         0
Collaborators                 119
Sex                             0
Age                             0
Phases                         88
Enrollment                      3
Funder Type                     0
Study Type                      0
Study Design                    2
Other IDs                       0
Start Date                      3
Primary Completion Date        10
Completion Date                 5
First Posted                    0
Results First Posted          134
Last Update Posted              0
Locations                       0
Study Documents               159
dtype: int64

In [17]:
df.duplicated().sum()   #shows 0 in the bracket which means none of the data is duplicated

np.int64(0)

In [31]:
columns_to_drop = ['Acronym', 'Study URL', 'Other IDs', 'Collaborators', 'Primary Outcome Measures', 'Secondary Outcome Measures', 'Other Outcome Measures', 'Primary Completion Date','First Posted','Results First Posted','Last Update Posted','Study Documents']

In [32]:
df_lean=df.drop(columns=columns_to_drop, errors='ignore')

In [33]:
print(f"success! you now have {len(df_lean.columns)} clean.columns.")
df_lean.head()

success! you now have 18 clean.columns.

,NCT Number,Study Title,Study Status,Brief Summary,Study Results,Conditions,Interventions,Sponsor,Sex,Age,Phases,Enrollment,Funder Type,Study Type,Study Design,Start Date,Completion Date,Locations
0,NCT03555344,Effect of Mantra on Hypertensive Patients,COMPLETED,Mantras are specialized energized sound or wor...,NO,High Blood Pressure,OTHER: Mantra Chikitsa,NMP Medical Research Institute,ALL,ADULT,NaN,96.0,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2017-10-28,2018-05-30,"NMP Medical Research Institute, Jaipur, Rajast..."
1,NCT01112306,ACT-293987 in Pulmonary Arterial Hypertension,COMPLETED,"Long-term, single-arm, multicenter, open-label...",YES,Pulmonary Arterial Hypertension,DRUG: ACT-293987,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,709.0,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2010-07-07,2021-08-26,"Mobile, Alabama, United States|Phoenix, Arizon..."
2,NCT01106014,Selexipag (ACT-293987) in Pulmonary Arterial H...,COMPLETED,The AC-065A302 (GRIPHON) study is an event-dri...,YES,Pulmonary Arterial Hypertension,DRUG: Selexipag|DRUG: Placebo,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,1156.0,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-12-01,2014-10-01,"University of South Alabama, Mobile, Alabama, ..."
3,NCT00660179,Study of Macitentan (ACT-064992) on Morbidity ...,COMPLETED,The AC-055-302/SERAPHIN study will be an event...,YES,Pulmonary Arterial Hypertension,DRUG: macitentan (ACT-064992)|DRUG: macitentan...,Actelion,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,742.0,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-05,2012-04,"University of Alabama at Birmingham, Birmingha..."
4,NCT00494533,Study of Intravenous Remodulin in Patients in ...,TERMINATED,"Multi-center, double-blind, placebo-controlled...",NO,Pulmonary Arterial Hypertension,DRUG: Remodulin (treprostinil sodium),United Therapeutics,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE4,45.0,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2005-03,2005-10,"SAL Hospital & Medical Institute, Ahmedabad, I..."

In [34]:
df_lean.isnull().sum()

NCT Number          0
Study Title         0
Study Status        0
Brief Summary       0
Study Results       0
Conditions          0
Interventions      14
Sponsor             0
Sex                 0
Age                 0
Phases             88
Enrollment          3
Funder Type         0
Study Type          0
Study Design        2
Start Date          3
Completion Date     5
Locations           0
dtype: int64

In [35]:
#dropping rows where the critical timeline is missing
df_clean=df_lean.dropna(subset=['Start Date', 'Completion Date']).copy()

In [36]:
#fill up the gaps
df_clean['Phases']=df_clean['Phases'].fillna('Not Specified')
df_clean['Interventions']=df_clean['Interventions'].fillna('Not Specified')
df_clean['Study Design']=df_clean['Study Design'].fillna('Not Reported')
df_clean['Enrollment']=df_clean['Enrollment'].fillna(0).astype(int)

In [37]:
df_clean.head()

,NCT Number,Study Title,Study Status,Brief Summary,Study Results,Conditions,Interventions,Sponsor,Sex,Age,Phases,Enrollment,Funder Type,Study Type,Study Design,Start Date,Completion Date,Locations
0,NCT03555344,Effect of Mantra on Hypertensive Patients,COMPLETED,Mantras are specialized energized sound or wor...,NO,High Blood Pressure,OTHER: Mantra Chikitsa,NMP Medical Research Institute,ALL,ADULT,Not Specified,96,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2017-10-28,2018-05-30,"NMP Medical Research Institute, Jaipur, Rajast..."
1,NCT01112306,ACT-293987 in Pulmonary Arterial Hypertension,COMPLETED,"Long-term, single-arm, multicenter, open-label...",YES,Pulmonary Arterial Hypertension,DRUG: ACT-293987,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,709,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2010-07-07,2021-08-26,"Mobile, Alabama, United States|Phoenix, Arizon..."
2,NCT01106014,Selexipag (ACT-293987) in Pulmonary Arterial H...,COMPLETED,The AC-065A302 (GRIPHON) study is an event-dri...,YES,Pulmonary Arterial Hypertension,DRUG: Selexipag|DRUG: Placebo,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,1156,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-12-01,2014-10-01,"University of South Alabama, Mobile, Alabama, ..."
3,NCT00660179,Study of Macitentan (ACT-064992) on Morbidity ...,COMPLETED,The AC-055-302/SERAPHIN study will be an event...,YES,Pulmonary Arterial Hypertension,DRUG: macitentan (ACT-064992)|DRUG: macitentan...,Actelion,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,742,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-05,2012-04,"University of Alabama at Birmingham, Birmingha..."
4,NCT00494533,Study of Intravenous Remodulin in Patients in ...,TERMINATED,"Multi-center, double-blind, placebo-controlled...",NO,Pulmonary Arterial Hypertension,DRUG: Remodulin (treprostinil sodium),United Therapeutics,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE4,45,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2005-03,2005-10,"SAL Hospital & Medical Institute, Ahmedabad, I..."

In [38]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [39]:
df_clean.shape

(167, 18)

In [40]:
df_clean.head(200)

,NCT Number,Study Title,Study Status,Brief Summary,Study Results,Conditions,Interventions,Sponsor,Sex,Age,Phases,Enrollment,Funder Type,Study Type,Study Design,Start Date,Completion Date,Locations
0,NCT03555344,Effect of Mantra on Hypertensive Patients,COMPLETED,Mantras are specialized energized sound or wor...,NO,High Blood Pressure,OTHER: Mantra Chikitsa,NMP Medical Research Institute,ALL,ADULT,Not Specified,96,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2017-10-28,2018-05-30,"NMP Medical Research Institute, Jaipur, Rajast..."
1,NCT01112306,ACT-293987 in Pulmonary Arterial Hypertension,COMPLETED,"Long-term, single-arm, multicenter, open-label...",YES,Pulmonary Arterial Hypertension,DRUG: ACT-293987,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,709,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2010-07-07,2021-08-26,"Mobile, Alabama, United States|Phoenix, Arizon..."
2,NCT01106014,Selexipag (ACT-293987) in Pulmonary Arterial H...,COMPLETED,The AC-065A302 (GRIPHON) study is an event-dri...,YES,Pulmonary Arterial Hypertension,DRUG: Selexipag|DRUG: Placebo,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,1156,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-12-01,2014-10-01,"University of South Alabama, Mobile, Alabama, ..."
3,NCT00660179,Study of Macitentan (ACT-064992) on Morbidity ...,COMPLETED,The AC-055-302/SERAPHIN study will be an event...,YES,Pulmonary Arterial Hypertension,DRUG: macitentan (ACT-064992)|DRUG: macitentan...,Actelion,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,742,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-05,2012-04,"University of Alabama at Birmingham, Birmingha..."
4,NCT00494533,Study of Intravenous Remodulin in Patients in ...,TERMINATED,"Multi-center, double-blind, placebo-controlled...",NO,Pulmonary Arterial Hypertension,DRUG: Remodulin (treprostinil sodium),United Therapeutics,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE4,45,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2005-03,2005-10,"SAL Hospital & Medical Institute, Ahmedabad, I..."
5,NCT00667823,Clinical Study to Assess the Long-term Safety ...,COMPLETED,The main objective of the AC 055 303/SERAPHIN ...,YES,Pulmonary Arterial Hypertension,DRUG: Macitentan,Actelion,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,550,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2008-10-17,2020-12-07,"University of Alabama at Birmingham, Birmingha..."
7,NCT04273945,Outcome Study Assessing a 75 Milligrams (mg) D...,ACTIVE_NOT_RECRUITING,The purpose of this study is to demonstrate su...,NO,Pulmonary Arterial Hypertension,DRUG: Macitentan 10 mg|DRUG: Macitentan 37.5 m...,Actelion,ALL,"ADULT, OLDER_ADULT",PHASE3,935,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2020-06-30,2029-02-20,"Mayo Clinic, Phoenix, Arizona, 85054, United S..."
8,NCT01027949,An Open-Label Extension Trial of UT-15C Sustai...,COMPLETED,This study provided/continued to provide oral ...,YES,Pulmonary Arterial Hypertension,DRUG: Oral Treprostinil,United Therapeutics,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,894,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2007-01-16,2020-02-12,"The Kirklin Clinic, Birmingham, Alabama, 35233..."
9,NCT01560637,"An Open-Label, Long-Term Study of Oral Trepros...",COMPLETED,"This study is an international, multi-center, ...",YES,Pulmonary Arterial Hypertension,DRUG: UT-15C (treprostinil diolamine),United Therapeutics,ALL,"ADULT, OLDER_ADULT",PHASE3,471,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2013-09-11,2021-08-12,"Arizona Pulmonary Specialists, Ltd., Phoenix, ..."
10,NCT00430716,To Assess The Efficacy and Safety Of Oral Sild...,TERMINATED,"To demonstrate a dose response for 1 mg, 5 mg ...",YES,Pulmonary Arterial Hypertension,DRUG: Sildenafil citrate|DRUG: Sildenafil citr...,Pfizer's Upjohn has merged with Mylan to form ...,ALL,"ADULT, OLDER_ADULT",PHASE4,130,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-04-08,2010-05-25,"Arizona Pulmonary Specialists, LTD, Phoenix, A..."
11,NCT01338415,FUTURE 3 Study Extension,COMPLETED,The objectives of the FUTURE 3 Study Extension...,YES,Pulmonary Arterial Hypertension,DRUG: Bosentan,Actelion,ALL,CHILD,PHASE3,58,INDUSTRY,INTERVENTIONAL,Allocation: NON_RANDOMIZED | Intervention Mode...,2011-03-08,2020-05-29,"The Children's Hospital - Site 9102, Aurora, C..."
12,NCT01560624,Phase III Clinical Worsening Study of UT-15C i...,COMPLETED,"This is an international, multicenter, randomi...",YES,Pulmonary Arterial Hypertension,DRUG: Treprostinil Diolamine|DRUG: Placebo,United Therapeutics,ALL,"ADULT, OLDER_ADULT",PHASE3,690,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2012-06-26,2018-06-24,"Arizona Pulmonary Specialists, Ltd., Phoenix, ..."
13,NCT06180096,Bioequivalence Study of Riociguat 2.5 mg Film ...,COMPLETED,Single dose oral bioequivalence study of Rioci...,NO,Pulmonary Arterial Hypertension,DRUG: Riociguat film coated tablets|DRUG: Adem...,Humanis Saglık Anonim Sirketi,MALE,ADULT,PHASE1,36,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: C...,2023-03-07,2023-04-06,"Cliantha Research Limited, Ahmedabad, Gujarat,..."
14,NCT00159874,A Long Term Extension Study Evaluating Safety ...,COMPLETED,"Active treatment, dose-blinded extension study...",YES,Pulmonary Arterial Hypertension,DRUG: Sildenafil citrate|DRUG: Sildenafil citr...,Pfizer's Upjohn has merged with Mylan to form ...,ALL,CHILD,PHASE3,234,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2004-01,2012-12,"Pfizer Investigational Site, Palo Alto, Califo..."
16,NCT00159913,"A Randomized, Double-Blind, Placebo-Controlled...",COMPLETED,This is a clinical research study designed to ...,YES,"Pulmonary Arterial Hypertension, Children",DRUG: Sildenafil citrate|DRUG: Sildenafil citr...,Pfizer's Upjohn has merged with Mylan to form ...,ALL,CHILD,PHASE3,235,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2003-08,2008-06,"Pfizer Investigational Site, Palo Alto, Califo..."
17,NCT03053739,To Compare the Efficacy of Combination Therapy...,UNKNOWN,The study will be carried out on 50 consecutiv...,NO,Associated Pulmonary Arterial Hypertension,DRUG: Sildenafil 20mg and Bosentan 62.5mg|DRUG...,Post Graduate Institute of Medical Education a...,ALL,"ADULT, OLDER_ADULT",PHASE4,50,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2016-12,2017-12,"Dr Preksha Dwivedi, Chandigarh, 160012, India"
18,NCT06948422,A Master Protocol for Orforglipron (LY3502970)...,RECRUITING,The GZPL master protocol will support 2 indepe...,NO,Hypertension,DRUG: Orforglipron|DRUG: Placebo,Eli Lilly and Company,ALL,"ADULT, OLDER_ADULT",PHASE3,974,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2025-04-30,2027-09,"Elite Clinical Studies, LLC, Phoenix, Arizona,..."
19,NCT06952530,A Master Protocol Study of Orforglipron (LY350...,RECRUITING,GZL2 is an independent study conducted under t...,NO,Hypertension,DRUG: Orforglipron|DRUG: Placebo,Eli Lilly and Company,ALL,"ADULT, OLDER_ADULT",PHASE3,487,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2025-04-30,2027-09,"Elite Clinical Studies, LLC, Phoenix, Arizona,..."
20,NCT05851040,Observe the Effect of Wheatgrass and Tulsi For...,UNKNOWN,Antioxidant qualities have been attributed to ...,NO,"Blood Pressure, High|Blood Sugar; High|Weight,...",OTHER: Observation study,Swalife Biotech,ALL,"ADULT, OLDER_ADULT",Not Specified,100,INDUSTRY,OBSERVATIONAL,Observational Model: COHORT | Time Perspective...,2023-05-10,2023-10-30,"Sinhgad college of Pharmacy, Pune, Maharashtra..."
21,NCT02147366,Indian Instrumental Music in Hypertension,COMPLETED,* Hypertension is one of the leading risk fact...,NO,Hypertension,BEHAVIORAL: Music & lifestyle changes|BEHAVIOR...,MS Ramaiah Medical College & Hospitals,ALL,ADULT,Not Specified,100,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2012-05,2013-07,"M S Ramaiah Medical college and hospitals, Ban..."
22,NCT06344104,A Study to Investigate the Efficacy and Safety...,ACTIVE_NOT_RECRUITING,The purpose of this study is to measure the ef...,NO,Uncontrolled Hypertension|Resistant Hypertension,DRUG: Baxdrostat|DRUG: Placebo,AstraZeneca,ALL,"ADULT, OLDER_ADULT",PHASE3,326,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2024-04-08,2026-04-03,"Research Site, Bahía Blanca, 8000, Argentina|R..."
23,NCT06034743,A Study to Investigate the Efficacy and Safety...,COMPLETED,"This is a Phase III, multicentre, randomised, ...",NO,Uncontrolled Hypertension|Resistant Hypertension,DRUG: Baxdrostat|DRUG: Placebo,AstraZeneca,ALL,"ADULT, OLDER_ADULT",PHASE3,796,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2023-11-22,2025-10-10,"Research Site, Saraland, Alabama, 36571, Unite..."
24,NCT00151775,Assessment of Efficacy and Safety of Olmesarta...,COMPLETED,This study assesses the efficacy and safety of...,YES,Hypertension,DRUG: olmesartan medoxomil|DRUG: placebo|DRUG:...,Daiichi Sankyo,ALL,CHILD,PHASE2|PHASE3,362,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2005-05,2008-09,"Birmingham, Alabama, United States|Phoenix, Ar..."
25,NCT00433836,Effect of Valsartan Compared to Enalapril on S...,COMPLETED,The purpose of this 12-week active controlled ...,YES,Hypertension,DRUG: Valsartan|DRUG: Enalapril,Novartis Pharmaceuticals,ALL,CHILD,PHASE3,300,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-01,2009-02,"Sites in USA, East Hanover, New Jersey, 07936,..."
26,NCT00435162,Dose Response of Valsartan on Sitting Systolic...,COMPLETED,The purpose of this study is to evaluate the s...,YES,Hypertension,DRUG: Valsartan 0.25 mg/kg|DRUG: Valsartan 1.0...,Novartis Pharmaceuticals,ALL,CHILD,PHASE3,74,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-03,2009-01,"Sites in USA, USA, New Jersey, United States|S..."
27,NCT00457626,A Study to Evaluate the Long-term Use of Valsa...,COMPLETED,The purpose of this study is to evaluate the e...,YES,Hypertension,DRUG: Valsartan,Novartis Pharmaceuticals,ALL,CHILD,PHASE3,66,INDUSTRY,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2007-04-09,2009-05-25,"Novartis Investigative Site, Hackensack, New J..."
28,NCT03164317,To Test the Effectiveness of a Trained Nurse L...,COMPLETED,This study evaluates the effect of a mobile he...,NO,Hypertension,OTHER: Intervention|OTHER: Control,"Centre for Chronic Disease Control, India",ALL,"ADULT, OLDER_ADULT",Not Specified,1872,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2018-08-20,2021-03-31,"Community Health Centre, Aganampudi, Andhra Pr..."
29,NCT00548067,Pharmacokinetic Drug Interaction Study Followi...,COMPLETED,The purpose of this study is to determine pote...,NO,Hypertension,DRUG: Valsartan/hydrochlorothiazide (HCTZ)|DRU...,Novartis,ALL,ADULT,PHASE3,111,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-09,2008-03,"Novartis Investigative Site, Ahmedabad, India|..."
30,NCT01219556,Xirtam H Combination In the Treatment of Hyper...,COMPLETED,This is post-marketing observational study in ...,NO,Hypertension,DRUG: Olmesartan plus hydrochlorothiazide (Xir...,Bayer,ALL,"ADULT, OLDER_ADULT",Not Specified,8704,INDUSTRY,OBSERVATIONAL,Observational Model: COHORT | Time Perspective...,2010-11,2013-02,"Many Locations, India"
31,NCT01527760,Effectiveness of Viscum Album Mother Tincture ...,COMPLETED,To estimate the effectiveness of Viscum album ...,NO,Hypertension,DRUG: Viscum album ethanolic extract manufactu...,Fr Muller Homoeopathic Medical College,ALL,"ADULT, OLDER_ADULT",Not Specified,37,OTHER,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2011-02,2011-09,Fr Muller Homoeopathic Medical College Hospita...
32,NCT00402103,An Assessment of Long Term Safety of the Combi...,COMPLETED,To assess the long-term (6 month and 12 month)...,YES,Hypertension,DRUG: Aliskiren|DRUG: Amlodipine|DRUG: Hydroch...,Novartis,ALL,"ADULT, OLDER_ADULT",PHASE3,556,INDUSTRY,INTERVENTIONAL,Allocation: NON_RANDOMIZED | Intervention Mode...,2006-11,2008-04,"Investigative Site, Santa Fe, New Mexico, Unit..."
33,NCT00446511,"Extension Study to Assess Long Term Safety, To...",COMPLETED,The purpose of this extension study is to comp...,YES,Hypertension,DRUG: Valsartan|DRUG: Enalapril|DRUG: placebo ...,Novartis Pharmaceuticals,ALL,CHILD,PHASE3,250,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-06,2009-06,"Sites in USA, East Hanover, New Jersey, 07936,..."
34,NCT00631917,A Study Evaluating the Gastrointestinal (GI) S...,COMPLETED,This study will evaluate the long-term gastroi...,YES,Hypertension,DRUG: Aliskiren|DRUG: Ramipril|OTHER: Placebo ...,Novartis,ALL,"ADULT, OLDER_ADULT",PHASE4,774,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-02,2009-09,"Investigative Site, Kansas City, Missouri, Uni..."
35,NCT00325403,FREEDOM - M: Oral Treprostinil as Monotherapy ...,COMPLETED,"This study was an international, multicenter, ...",YES,Pulmonary Hypertension,DRUG: Oral treprostinil (UT-15C) Sustained Rel...,United Therapeutics,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,349,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2006-10,2011-04,"University of Alabama-Birmingham, Birmingham, ..."
37,NCT00389519,A Study of the Effectiveness and Safety of Ram...,TERMINATED,The primary purpose of this study is to evalua...,YES,Hypertension,DRUG: ramipril|DRUG: placebo,Pfizer,ALL,CHILD,PHASE3,422,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2006-10,2007-11,UAMS College of Medicine/ Arkansas Children's ...
38,NCT00529451,"Safety and Efficacy of Aliskiren 300 mg, 150 m...",COMPLETED,This study is designed to investigate the effi...,YES,Hypertension,DRUG: Aliskiren|DRUG: Ramipril,Novartis,ALL,"ADULT, OLDER_ADULT",PHASE3,1613,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-09,2008-07,"Novartis Investigative Sites, China, China|Nov..."
39,NCT00500604,Efficacy of Irbesartan/Hydrochlorothiazide Ver...,COMPLETED,The primary objective is to compare the effica...,NO,Hypertension,DRUG: Irbesartan/hydrochlorothiazide|DRUG: Val...,Sanofi,ALL,"ADULT, OLDER_ADULT",PHASE4,1617,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2007-07,2010-01,"Sanofi-Aventis Administrative Office, Cairo, E..."
40,NCT00795639,Sitaxsentan Efficacy And Safety Trial With A R...,TERMINATED,This protocol is for subjects with pulmonary a...,YES,Pulmonary Arterial Hypertension|Pulmonary Hype...,DRUG: Sitaxsentan|DRUG: Placebo,Pfizer,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,183,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-12,2011-03,"Pfizer Investigational Site, Fountain Valley, ..."
41,NCT00147589,A Study to Evaluate the Efficacy and Safety of...,COMPLETED,"To evaluate the efficacy, safety, and tolerati...",NO,Hypertension,DRUG: Eplerenone,Pfizer's Upjohn has merged with Mylan to form ...,ALL,CHILD,PHASE3,320,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2004-09,2007-01,"Pfizer Investigational Site, Little Rock, Arka..."
42,NCT00147615,The Long-term Study to Evaluate the Safety of ...,COMPLETED,To assess the long-term safety and toleration ...,NO,Hypertension,DRUG: Eplerenone,Pfizer's Upjohn has merged with Mylan to form ...,ALL,CHILD,PHASE3,140,INDUSTRY,INTERVENTIONAL,Allocation: NON_RANDOMIZED | Intervention Mode...,2004-10,2006-06,"Pfizer Investigational Site, Los Angeles, Cali..."
43,NCT00796666,Study Looking at Combination Therapy (Sitaxsen...,TERMINATED,As monotherapy for pulmonary arterial hyperten...,YES,Pulmonary Arterial Hypertension|Pulmonary Hype...,DRUG: Sitaxsentan|DRUG: Sitaxsentan and Silden...,Pfizer,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE3,131,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-05,2011-03,"Pfizer Investigational Site, Fountain Valley, ..."
44,NCT02094924,A Relative Bioavailability Study of a Fixed Do...,COMPLETED,This study is required to confirm the suitabil...,NO,Hypertension,DRUG: GSK587323|DRUG: FDC of candesartan cilex...,GlaxoSmithKline,ALL,"ADULT, OLDER_ADULT",PHASE1,16,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: C...,2014-04-17,2014-05-23,"GSK Investigational Site, Hyderabad, 500 013, ..."
45,NCT00950066,Irbesartan and Amlodipine Combination in Contr...,COMPLETED,The primary objective is to compare the extent...,NO,Hypertension,DRUG: IRBESARTAN (SR47436)|DRUG: Amlodipine|DR...,Sanofi,ALL,"ADULT, OLDER_ADULT",PHASE2,270,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-07,2010-01,"Sanofi-Aventis Administrative Office, Mumbai, ..."
46,NCT00853112,A Research Study To Assess The Effectiveness A...,TERMINATED,Study will assess PF-00489791 efficacy and saf...,YES,"Hypertension, Pulmonary",DRUG: PF-00489791|DRUG: PF-00489791|DRUG: PF-0...,Pfizer,ALL,"ADULT, OLDER_ADULT",PHASE2,48,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2009-04,2010-07,"Pulmonary Associates, PA, Phoenix, Arizona, 85..."
48,NCT00777946,Study to Evaluate the Efficacy and Safety of C...,COMPLETED,This study will assess the safety and efficacy...,YES,Hypertension,DRUG: Aliskiren 300 mg|DRUG: Aliskiren/Amlodip...,Novartis,ALL,"ADULT, OLDER_ADULT",PHASE3,818,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2008-10,2009-05,"Investigative site, Estonia, Estonia|Investiga..."
49,NCT02691585,Indian Ragas on Health - a Electrophysiologica...,COMPLETED,Blood pressure (BP) reduced significantly afte...,NO,Hypertension,OTHER: Music Intervention,MS Ramaiah Medical College & Hospitals,ALL,ADULT,Not Specified,160,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2016-01,2019-07-30,"M S Ramaiah Medical college and hospitals, Ban..."
50,NCT02006602,Bioavailability Study of Candesartan Cilexetil...,COMPLETED,"This will be an open-label, randomized, single...",NO,Hypertension,"DRUG: Candesartan cilexetil (GW615775, Test fo...",GlaxoSmithKline,ALL,"ADULT, OLDER_ADULT",PHASE1,16,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: C...,2013-12-13,2014-01-22,"GSK Investigational Site, Hyderabad, 500 013, ..."
51,NCT02006589,Bioavailability Study of Candesartan Cilexetil...,COMPLETED,"This will be an open-label, randomized, single...",NO,Hypertension,"DRUG: Candesartan cilexetil (GW615775, Test fo...",GlaxoSmithKline,ALL,"ADULT, OLDER_ADULT",PHASE1,16,INDUSTRY,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: C...,2013-12-11,2014-01-22,"GSK Investigational Site, Hyderabad, 500 013, ..."
52,NCT00930722,A Non Interventional Study To Asses The Safety...,COMPLETED,"This is a prospective, non-interventional, non...",YES,Hypertension,DRUG: quinapril,Pfizer,ALL,"ADULT, OLDER_ADULT",Not Specified,329,INDUSTRY,OBSERVATIONAL,Observational Model: CASE_ONLY | Time Perspect...,2009-06,2010-06,"Pfizer Investigational Site, Patna, Bihar, 01,..."
53,NCT03803306,Vedic Medical Astrology in Essential Hypertension,COMPLETED,Previous studies have explored the correlation...,NO,Essential Hypertension,COMBINATION_PRODUCT: Vedic Medical Astrology|O...,NMP Medical Research Institute,ALL,ADULT,Not Specified,68,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,2018-07-12,2019-01-06,"NMP Medical Reserach Institute, Jaipur, Rajast..."

In [41]:
df_clean.isnull().sum()

NCT Number         0
Study Title        0
Study Status       0
Brief Summary      0
Study Results      0
Conditions         0
Interventions      0
Sponsor            0
Sex                0
Age                0
Phases             0
Enrollment         0
Funder Type        0
Study Type         0
Study Design       0
Start Date         0
Completion Date    0
Locations          0
dtype: int64

In [44]:
import os
desktop=os.path.join(os.path.join(os.environ['USERPROFILE']),'Desktop')
file_path=os.path.join(desktop,'Hypertension_India_cleaned.xlsx')
df_clean.to_excel(file_path, index=False)
print(f"File is successfully saved as: {file_path}")

File is successfully saved as: C:\Users\HYDERA\Desktop\Hypertension_India_cleaned.xlsx